development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://wdfayserver.herokuapp.com/"
  secret_token: "batkaro"
  signature_expiration: 86400 # one day
