development:
  server: "https://wdfayserver.herokuapp.com/"
  secret_token: "batkaro"
test:
  server: "https://wdfayserver.herokuapp.com/"
  secret_token: "batkaro"
production:
  server: "https://wdfayserver.herokuapp.com/"
  secret_token: "batkaro"
  signature_expiration: 86400 # one day
